### PR TITLE
Ran auto-rubocop for your project

### PR DESCRIPTION
**Pull request by jjasghar**
It should get you closer to the standard you are looking for. It's was
failing in the Chef Partner Cookbook Program CI, just helping yall along.

/cc @russellseymour @martinb3 

Signed-off-by: JJ Asghar <jj@chef.io>

### CODE REVIEW

**Comment by martinb3** [comment]
Hey! @jjasghar, is there a place I could look to confirm the Partner CI job for this cookbook is passing or failing? I think I've built on your PR and have all the style/lint stuff passing.

**Comment by jjasghar** [comment]
https://cpcp.chef.io/job/rackspace_monitoring-cookbook/

We are updating the CI environment, even has it's own hostname now!

**Comment by martinb3** [comment]
I don't seem to be able to re-run the job, but the linting is passing for me :)

**Comment by jjasghar** [comment]
Yay!

Now Foodcritic. :(

```
FC066: Ensure chef_version is set in metadata: ./metadata.rb:1
FC067: Ensure at least one platform supported in metadata: ./metadata.rb:1
FC069: Ensure standardized license defined in metadata: ./metadata.rb:1
FC078: Ensure cookbook shared under an OSI-approved open source license: ./metadata.rb:1
FC113: Resource declares deprecated use_inline_resources: ./libraries/provider_rackspace_monitoring_check.rb:11
FC113: Resource declares deprecated use_inline_resources: ./libraries/provider_rackspace_monitoring_service.rb:11
```

https://cpcp.chef.io/job/rackspace_monitoring-cookbook/206/console

**Comment by martinb3** [comment]
As far as I can tell, those are warnings -- the build wasn't failing for me. We're supporting older Chef right now, so I don't think I want to just break all of that stuff without more testing 👍

**Pull request merged**
