### PR TITLE
Add missing agent types

### PR DESCRIPTION
**Pull request by mburns**
Added a local branch to enable CI testing. Deprecates #4

### CODE REVIEW

**Comment by mburns** [comment]
/CC @martinb3 

> The only thing I noticed was that the templates added all look like basically the same template, with the label and id changed. Perhaps only one template is necessary? But either way, looks great so far.

I noticed that too and couldn't decide if it would be better to consolidate that logic or not. From my viewing, all the `agent.*.conf.erb` templates could be implemented using just `agent.custom.conf.erb` with some more logic added in the provider class.

The two differences I see are that (1) some of the templates include the `details` section, which could be conditionally included, and (2) alarm names that are some variation of the check `type`. As the individual checks get more elaborate or flexible, we might benefit from keeping that logic in separate templates and not bloating `provider_rackspace_monitoring_check`. _shrug_

**Comment by martinb3** [comment]
> The two differences I see are that (1) some of the templates include the details section, which could be conditionally included, and
> (2) alarm names that are some variation of the check type. 
> As the individual checks get more elaborate or flexible, we might benefit from keeping that logic in separate templates and not bloating provider_rackspace_monitoring_check. shrug

I agree with you completely. Perhaps we should use two templates -- a default one and then specific ones if we need to override anything more substantial?

**Comment by mburns** [comment]
Sorry this went quiet for a while. I now have tests passing with the new [apache](https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/wiki/Agent.apache), [mysql](https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/wiki/Agent.mysql) and [redis](https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/wiki/Agent.redis) agent checks. They former two checks include stubbed/simple alarms because there is not an obvious common case, afaik. Happy to add one if there is a suggestion.

I implemented these checks in the same way the existing checks are implemented. I'd like to do a follow-up PR to (1) refactor the check templates and (2) simplify/document the steps required to adding new checks.

**Comment by martinb3** [comment]
This all looks good to me.

**Pull request merged**
